---
name: 'Kusari Ingest'
description: 'Ingest files into Kusari Platform'
branding:
  icon: "shield"
  color: "purple"
author: 'Kusari'
inputs:
  files:
    description: 'Path to directory or specific file to ingest'
    required: true
  api-addr:
    description: 'Kusari hosted GUAC tenant api endpoint'
    required: true
  client-id:
    description: 'Client id for auth token provider'
    required: true
  client-secret:
    description: 'Client secret for auth token provider'
    required: true
  token-url:
    description: 'Url for auth token provider'
    required: true
    default: https://auth.us.kusari.cloud/oauth2/token
  alias:
    description: 'Alias of the package for grouping'
    required: false
    default: ""
  type:
    description: 'Type of the file being uploaded'
    required: false
    default: ""
outputs:
  console_out:
    description: 'GUAC ingestion output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--file-path=${{ inputs.files }}"
    - "--client-id=${{ inputs.client-id }}"
    - "--client-secret=${{ inputs.client-secret }}"
    - "--tenant-endpoint=${{ inputs.api-addr }}"
    - "--token-endpoint=${{ inputs.token-url }}"
    - "--alias=${{ inputs.alias }}"
    - "--document-type=${{ inputs.type }}"
