---
name: 'Kusari Ingest'
description: 'Ingest files into Kusari Platform'
branding:
  icon: "shield"
  color: "purple"
author: 'Kusari'
inputs:
  file-path:
    description: 'Path to directory or specific file to ingest'
    required: true
  tenant-endpoint:
    description: 'Kusari Platform tenant api endpoint'
    required: true
  client-id:
    description: 'Client id for auth token provider'
    required: true
  client-secret:
    description: 'Client secret for auth token provider'
    required: true
  token-endpoint:
    description: 'Kusari Platform auth token provider endpoint'
    required: true
    default: https://auth.us.kusari.cloud/oauth2/token
  alias:
    description: 'Alias of the package for grouping'
    required: false
    default: ""
  document-type:
    description: 'Type of the file being uploaded'
    required: false
    default: ""
  open-vex:
    description: 'Set to true if ingesting an OpenVEX document. When true, tag is required and so is one of software-id and sbom-subject.'
    required: false
    default: "false"
  tag:
    description: 'Tag for the document. Currently only used for OpenVEX. Example: govulncheck'
    required: false
  software-id:
    description: 'Kusari Platform software ID that the document applies to. Currently only used for OpenVEX. Example: 1234'
    required: false
  sbom-subject:
    description: 'Kusari Platform software SBOM subject substring value that uniquely indicates which software that the document applies to. Currently only used for OpenVex. Example: kusari-ingest'
    required: false
  component-name:
    description: 'Kusari Platform software component name (multiple SBOM subjects can belong to the same component). If a component with this name does not exist, it will be created. Optional. Example: kusari-ingest'
    required: false
    default: ${{ github.event.repository.name }}
  check-blocked-packages:
    description: Check SBOM dependencies against the Blocked Package list in the Kusari Platform.
    required: false
    default: "false"
  sbom-subject-name-override:
    description: 'SBOM Subject Name override (optional, for SBOMs only)'
    required: false
    default: ""
  sbom-subject-version-override:
    description: 'SBOM Subject Version override (optional, for SBOMs only)'
    required: false
    default: ""
outputs:
  console_out:
    description: 'Kusari Platform ingestion output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--file-path=${{ inputs.file-path }}"
    - "--client-id=${{ inputs.client-id }}"
    - "--client-secret=${{ inputs.client-secret }}"
    - "--tenant-endpoint=${{ inputs.tenant-endpoint }}"
    - "--token-endpoint=${{ inputs.token-endpoint }}"
    - "--alias=${{ inputs.alias }}"
    - "--document-type=${{ inputs.document-type }}"
    - "--open-vex=${{ inputs.open-vex }}"
    - "--tag=${{ inputs.tag }}"
    - "--software-id=${{ inputs.software-id }}"
    - "--sbom-subject=${{ inputs.sbom-subject }}"
    - "--component-name=${{ inputs.component-name }}"
    - "--check-blocked-packages=${{ inputs.check-blocked-packages }}"
    - "--sbom-subject-name-override=${{ inputs.sbom-subject-name-override }}"
    - "--sbom-subject-version-override=${{ inputs.sbom-subject-version-override }}"
